<?php

namespace Account\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoreUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoreUserRepository extends EntityRepository
{
}
