<?php

namespace Account\AccountBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoreGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoreGroupRepository extends EntityRepository
{
}
